### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by romanmatushkin** [kirmarchenko/pyproxyhunter#2]
At the moment there is no way to understand how much work done, would be great to see some progress bar to understand if you have got a couple of minutes for sex or ten minutes for coffee.

It'd be useful to see how much good proxies are found already in order to make decision if you are ready to Ctrl-C the script.

**Comment by kirmarchenko** [comment]
Hey @romanmatushkin , thanks for the suggestion! This feature is already in master branch. Also, your request from #3 is in master too. Please, update your local code and let me know if you are happy with these changes.

Best regards,
@KirillMarchenko

**Comment by romanmatushkin** [comment]
@kirmarchenko, this is fucking awesome! 👍
